# Generated by Django 5.2.6 on 2025-10-18 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemilangProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(max_length=1000)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gemilang_products',
                'indexes': [models.Index(fields=['name'], name='gemilang_pr_name_1642b5_idx'), models.Index(fields=['created_at'], name='gemilang_pr_created_f32f7b_idx')],
            },
        ),
    ]
