# Generated by Django 5.2.6 on 2025-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0002_gemilangproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemilangproduct',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
