# Generated by Django 5.1.2 on 2025-09-22 16:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0002_item_province_unit_remove_price_material_itemprice_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemprice',
            name='unique_latest_per_item_province',
        ),
        migrations.AddField(
            model_name='itemprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='itemprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('item', 'province'), name='uq_latest_price_per_item_province'),
        ),
    ]
