# Generated by Django 5.2.7 on 2025-10-22 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0003_gemilangproduct_unit_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemilangproduct',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='DepoBangunanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(max_length=1000)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'depobangunan_products',
                'indexes': [models.Index(fields=['name'], name='depobanguna_name_ed2377_idx'), models.Index(fields=['created_at'], name='depobanguna_created_396ca6_idx')],
            },
        ),
    ]
