# Generated by Django 5.0.6 on 2025-10-20 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0003_gemilangproduct_unit_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemilangproduct',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Mitra10Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(max_length=1000)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mitra10_products',
                'indexes': [models.Index(fields=['name'], name='mitra10_pro_name_8e58e0_idx'), models.Index(fields=['created_at'], name='mitra10_pro_created_406fc6_idx')],
            },
        ),
    ]
