# Generated by Django 5.2.6 on 2025-10-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0003_gemilangproduct_unit_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemilangproduct',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
