# Generated by Django 5.2.6 on 2025-10-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0004_alter_gemilangproduct_unit'),
        ('db_pricing', '0004_alter_gemilangproduct_unit_depobangunanproduct'),
        ('db_pricing', '0004_alter_gemilangproduct_unit_mitra10product'),
    ]

    operations = [
    ]
