# Generated by Django 5.2.7 on 2025-10-22 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0004_alter_gemilangproduct_unit_depobangunanproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuraganMaterialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(max_length=1000)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'juragan_material_products',
                'indexes': [models.Index(fields=['name'], name='juragan_mat_name_947224_idx'), models.Index(fields=['created_at'], name='juragan_mat_created_0239e7_idx')],
            },
        ),
    ]
