# Generated by Django 5.0.6 on 2025-10-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0005_merge_20251022_1759'),
        ('db_pricing', '0005_merge_20251022_2312'),
    ]

    operations = [
    ]
