# Generated by Django 5.2.7 on 2025-10-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0005_juraganmaterialproduct'),
        ('db_pricing', '0006_merge_20251023_0048'),
    ]

    operations = [
    ]
