# Generated by Django 5.2.7 on 2025-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0007_merge_20251024_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='juraganmaterialproduct',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
