# Generated by Django 5.2.3 on 2025-11-01 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0008_juraganmaterialproduct_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokopediaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(max_length=1000)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tokopedia_products',
                'indexes': [models.Index(fields=['name'], name='tokopedia_p_name_d5f968_idx'), models.Index(fields=['created_at'], name='tokopedia_p_created_79d19d_idx')],
            },
        ),
    ]
