# Generated by Django 5.2.6 on 2025-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0008_juraganmaterialproduct_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='depobangunanproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gemilangproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='juraganmaterialproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mitra10product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='depobangunanproduct',
            index=models.Index(fields=['category'], name='depobanguna_categor_60df8a_idx'),
        ),
        migrations.AddIndex(
            model_name='gemilangproduct',
            index=models.Index(fields=['category'], name='gemilang_pr_categor_ec6813_idx'),
        ),
        migrations.AddIndex(
            model_name='juraganmaterialproduct',
            index=models.Index(fields=['category'], name='juragan_mat_categor_dd5bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='mitra10product',
            index=models.Index(fields=['category'], name='mitra10_pro_categor_bab8ff_idx'),
        ),
    ]
