# Generated by Django 5.2.7 on 2025-11-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0009_depobangunanproduct_category_and_more'),
        ('db_pricing', '0009_tokopediaproduct'),
    ]

    operations = [
    ]
