# Generated by Django 5.2.7 on 2025-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0009_depobangunanproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemilangproduct',
            name='location',
            field=models.TextField(default='', max_length=200),
        ),
    ]
