# Generated by Django 5.0.6 on 2025-11-10 04:49

from django.db import migrations, models
from django.db.models import Value


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0010_merge_20251105_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitra10product',
            name='location',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='depobangunanproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, db_default=''),
        ),
        migrations.AlterField(
            model_name='gemilangproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, db_default=''),
        ),
        migrations.AlterField(
            model_name='juraganmaterialproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, db_default=''),
        ),
        migrations.AlterField(
            model_name='mitra10product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, db_default=''),
        ),
    ]
