# Generated by Django 5.2.7 on 2025-11-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0010_gemilangproduct_location'),
        ('db_pricing', '0010_merge_20251105_1718'),
    ]

    operations = [
    ]
