# Generated by Django 5.2.7 on 2025-11-08 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0010_merge_20251105_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depobangunanproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gemilangproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='juraganmaterialproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mitra10product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='PriceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('gemilang', 'Gemilang'), ('mitra10', 'Mitra10'), ('tokopedia', 'Tokopedia'), ('depobangunan', 'Depo Bangunan'), ('juragan_material', 'Juragan Material')], max_length=50)),
                ('product_name', models.CharField(max_length=500)),
                ('product_url', models.URLField(max_length=1000)),
                ('unit', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('old_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('new_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'price_anomalies',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['vendor'], name='price_anoma_vendor_109c2e_idx'), models.Index(fields=['status'], name='price_anoma_status_44b65c_idx'), models.Index(fields=['detected_at'], name='price_anoma_detecte_2cb32c_idx'), models.Index(fields=['product_name'], name='price_anoma_product_66444d_idx')],
            },
        ),
    ]
