# Generated by Django 5.2.6 on 2025-11-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0010_merge_20251105_1718'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE juragan_material_products MODIFY category VARCHAR(100) NULL DEFAULT ''",
            reverse_sql="ALTER TABLE juragan_material_products MODIFY category VARCHAR(100) NOT NULL"
        ),
    ]
