# Generated by Django 5.2.7 on 2025-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0010_merge_20251105_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokopediaproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
