# Generated by Django 5.0.6 on 2025-11-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0011_mitra10product_location_and_more'),
    ]

    operations = [
    ]
