# Generated by Django 5.2.7 on 2025-11-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0011_merge_20251112_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemilangproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
