# Generated by Django 5.2.7 on 2025-11-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0011_alter_depobangunanproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depobangunanproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, db_default=''),
        ),
        migrations.AlterField(
            model_name='gemilangproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, db_default=''),
        ),
        migrations.AlterField(
            model_name='juraganmaterialproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, db_default=''),
        ),
        migrations.AlterField(
            model_name='mitra10product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, db_default=''),
        ),
    ]
