# Generated by Django 5.2.7 on 2025-11-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0012_set_category_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceanomaly',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied to Database')], default='pending', max_length=20),
        ),
    ]
