# Generated by Django 5.2.7 on 2025-11-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0011_tokopediaproduct_category'),
        ('db_pricing', '0012_fix_category_default'),
    ]

    operations = [
    ]
