# Generated by Django 5.2.7 on 2025-11-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0011_fix_juragan_material_category_nullable'),
        ('db_pricing', '0012_set_category_default'),
    ]

    operations = [
    ]
