# Generated by Django 5.2.7 on 2025-11-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0012_fix_category_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='depobangunanproduct',
            name='location',
            field=models.TextField(default='', max_length=200),
        ),
    ]
