# Generated by Django 5.2.7 on 2025-11-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0013_merge_20251110_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='depobangunanproduct',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='gemilangproduct',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mitra10product',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tokopediaproduct',
            name='category',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='juraganmaterialproduct',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
