# Generated by Django 5.2.7 on 2025-11-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0013_merge_20251110_1005'),
    ]

    operations = [
        # Note: AddField operations for depobangunanproduct.location, gemilangproduct.location,
        # mitra10product.location, and tokopediaproduct.category were removed as these columns
        # were already added in earlier migrations (0013, 0010, 0011 respectively)
        migrations.AlterField(
            model_name='juraganmaterialproduct',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
