# Generated by Django 5.2.7 on 2025-11-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0013_depobangunanproduct_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depobangunanproduct',
            name='location',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
