# Generated by Django 5.2.7 on 2025-11-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0013_add_applied_status'),
        ('db_pricing', '0013_merge_20251110_1005'),
    ]

    operations = [
    ]
