# Generated by Django 5.2.7 on 2025-11-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0013_merge_20251111_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokopediaproduct',
            name='category',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='tokopediaproduct',
            index=models.Index(fields=['category'], name='tokopedia_p_categor_a32c62_idx'),
        ),
    ]
