# Generated by Django 5.2.7 on 2025-11-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0014_alter_tokopediaproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juraganmaterialproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
