# Generated by Django 5.2.7 on 2025-11-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0011_tokopediaproduct_category'),
        ('db_pricing', '0014_alter_depobangunanproduct_location'),
    ]

    operations = [
    ]
