# Generated by Django 5.2.7 on 2025-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0015_add_category_default_juragan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juraganmaterialproduct',
            name='category',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
    ]
