# Generated by Django 5.2.7 on 2025-11-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0015_merge_20251112_0753'),
        ('db_pricing', '0016_alter_juraganmaterialproduct_category'),
    ]

    operations = [
    ]
