# Generated by Django 5.2.7 on 2025-11-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0012_alter_gemilangproduct_category'),
        ('db_pricing', '0017_merge_20251112_0812'),
    ]

    operations = [
    ]
