# Generated by Django 5.2.7 on 2025-11-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0014_merge_20251111_2333'),
        ('db_pricing', '0018_merge_20251112_1937'),
    ]

    operations = [
    ]
