# Generated by Django 5.2.7 on 2025-11-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0014_depobangunanproduct_location_and_more'),
        ('db_pricing', '0019_merge_20251112_2248'),
    ]

    operations = [
    ]
