# Generated by Django 5.2.7 on 2025-11-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_pricing', '0010_merge_20251105_1416'),
        ('db_pricing', '0019_merge_20251112_2248'),
    ]

    operations = [
    ]
