# Generated by Django 5.2.6 on 2025-09-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('item_price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.itempricegroup')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPriceProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.itemprice')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.province')),
            ],
            options={
                'unique_together': {('item_price', 'province')},
            },
        ),
    ]
