# Generated by Django 5.2.6 on 2025-10-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingVendorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Name of the product', max_length=255)),
                ('price', models.CharField(help_text='Price of the product', max_length=255)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=255)),
                ('vendor', models.CharField(help_text='Vendor name', max_length=255)),
                ('location', models.CharField(help_text='Location where the product is available', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraping Vendor Data',
                'verbose_name_plural': 'Scraping Vendor Data',
                'db_table': 'scraping_vendor_data',
            },
        ),
    ]
